# Generated by Django 5.2.9 on 2026-01-03 22:28

import django.core.validators
import django.db.models.deletion
import secrets
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AvailabilityPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="公開URLで使用される一意の識別子",
                        max_length=100,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(3)],
                        verbose_name="スラッグ",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="予約ページのタイトル",
                        max_length=200,
                        verbose_name="タイトル",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="予約ページの説明",
                        verbose_name="説明",
                    ),
                ),
                (
                    "timezone_name",
                    models.CharField(
                        default="Asia/Tokyo", max_length=50, verbose_name="タイムゾーン"
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="各予約の長さ",
                        verbose_name="予約時間（分）",
                    ),
                ),
                (
                    "buffer_minutes",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="予約間の空き時間",
                        verbose_name="バッファ時間（分）",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="予約ページを公開するか",
                        verbose_name="公開",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="予約を受け付けるか",
                        verbose_name="有効",
                    ),
                ),
                (
                    "notify_on_booking",
                    models.BooleanField(
                        default=True,
                        help_text="予約があった時にメールで通知",
                        verbose_name="予約時通知",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_pages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="オーナー",
                    ),
                ),
            ],
            options={
                "verbose_name": "予約ページ",
                "verbose_name_plural": "予約ページ",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AvailabilitySlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_at", models.DateTimeField(verbose_name="開始日時")),
                ("end_at", models.DateTimeField(verbose_name="終了日時")),
                (
                    "is_booked",
                    models.BooleanField(default=False, verbose_name="予約済み"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="oneonone.availabilitypage",
                        verbose_name="予約ページ",
                    ),
                ),
            ],
            options={
                "verbose_name": "空き枠",
                "verbose_name_plural": "空き枠",
                "ordering": ["start_at"],
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="識別子",
                    ),
                ),
                (
                    "cancel_token",
                    models.CharField(
                        default=secrets.token_urlsafe,
                        max_length=64,
                        verbose_name="キャンセルトークン",
                    ),
                ),
                (
                    "guest_name",
                    models.CharField(max_length=100, verbose_name="ゲスト名"),
                ),
                (
                    "guest_email",
                    models.EmailField(
                        max_length=254, verbose_name="ゲストメールアドレス"
                    ),
                ),
                (
                    "guest_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="ゲストからのメッセージ",
                        verbose_name="メッセージ",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "確認中"),
                            ("confirmed", "確定"),
                            ("cancelled", "キャンセル"),
                            ("completed", "完了"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "meeting_url",
                    models.URLField(
                        blank=True, max_length=500, null=True, verbose_name="会議URL"
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="確定日時"
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="キャンセル日時"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "slot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking",
                        to="oneonone.availabilityslot",
                        verbose_name="予約枠",
                    ),
                ),
            ],
            options={
                "verbose_name": "予約",
                "verbose_name_plural": "予約",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="availabilityslot",
            constraint=models.UniqueConstraint(
                fields=("page", "start_at"), name="unique_slot_per_time"
            ),
        ),
    ]
