# Generated by Django 5.2.9 on 2026-01-03 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timezone_name",
                    models.CharField(
                        default="Asia/Tokyo", max_length=50, verbose_name="タイムゾーン"
                    ),
                ),
                (
                    "email_notifications",
                    models.BooleanField(default=True, verbose_name="メール通知"),
                ),
                (
                    "avatar_url",
                    models.URLField(blank=True, null=True, verbose_name="アバターURL"),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        choices=[
                            ("ja", "日本語"),
                            ("en", "English"),
                            ("zh-hans", "简体中文"),
                            ("zh-hant", "繁體中文"),
                            ("ko", "한국어"),
                            ("vi", "Tiếng Việt"),
                            ("pt", "Português"),
                        ],
                        default="ja",
                        help_text="UIとメール通知の言語",
                        max_length=10,
                        verbose_name="優先言語",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "ユーザープロファイル",
                "verbose_name_plural": "ユーザープロファイル",
            },
        ),
        migrations.CreateModel(
            name="UserIntegration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("google", "Google"),
                            ("outlook", "Outlook (Microsoft)"),
                            ("zoom", "Zoom"),
                        ],
                        max_length=50,
                        verbose_name="プロバイダー",
                    ),
                ),
                (
                    "_access_token_encrypted",
                    models.TextField(
                        db_column="access_token_encrypted",
                        verbose_name="アクセストークン（暗号化）",
                    ),
                ),
                (
                    "_refresh_token_encrypted",
                    models.TextField(
                        blank=True,
                        db_column="refresh_token_encrypted",
                        null=True,
                        verbose_name="リフレッシュトークン（暗号化）",
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="トークン有効期限")),
                (
                    "scopes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="スペース区切りのスコープ一覧",
                        verbose_name="許可スコープ",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="無効化日時"
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最終使用日時"
                    ),
                ),
                (
                    "last_error",
                    models.TextField(blank=True, null=True, verbose_name="最終エラー"),
                ),
                (
                    "error_count",
                    models.PositiveIntegerField(default=0, verbose_name="エラー回数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "外部連携",
                "verbose_name_plural": "外部連携",
                "indexes": [
                    models.Index(
                        fields=["user", "provider"],
                        name="accounts_us_user_id_c6ebdc_idx",
                    ),
                    models.Index(
                        fields=["is_active"], name="accounts_us_is_acti_606ffa_idx"
                    ),
                ],
                "unique_together": {("user", "provider")},
            },
        ),
    ]
