# Generated by Django 5.2.9 on 2026-01-03 22:35

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_at",
                    models.DateTimeField(
                        help_text="候補の開始日時", verbose_name="開始日時"
                    ),
                ),
                (
                    "end_at",
                    models.DateTimeField(
                        help_text="候補の終了日時", verbose_name="終了日時"
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="この候補に関する備考",
                        max_length=200,
                        verbose_name="備考",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="表示順序", verbose_name="表示順"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
            ],
            options={
                "verbose_name": "候補日程",
                "verbose_name_plural": "候補日程",
                "ordering": ["order", "start_at"],
            },
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="URL共有用の一意識別子",
                        unique=True,
                        verbose_name="識別子",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="イベント名",
                        max_length=200,
                        validators=[django.core.validators.MinLengthValidator(1)],
                        verbose_name="イベント名",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="イベントの説明・メモ",
                        verbose_name="説明",
                    ),
                ),
                (
                    "owner_name",
                    models.CharField(
                        help_text="主催者の名前", max_length=100, verbose_name="主催者"
                    ),
                ),
                (
                    "owner_email",
                    models.EmailField(
                        blank=True,
                        help_text="通知を受け取るメールアドレス（オプション）",
                        max_length=254,
                        null=True,
                        verbose_name="主催者メールアドレス",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="所属",
                        max_length=200,
                        verbose_name="所属",
                    ),
                ),
                (
                    "edit_key",
                    models.CharField(
                        blank=True,
                        help_text="移行期間中のみ使用。新規作成では使用しない",
                        max_length=100,
                        null=True,
                        verbose_name="編集キー（旧・平文）",
                    ),
                ),
                (
                    "edit_key_hash",
                    models.CharField(
                        blank=True,
                        help_text="イベント編集用のパスワード（ハッシュ保存）",
                        max_length=256,
                        null=True,
                        verbose_name="編集キー（ハッシュ）",
                    ),
                ),
                (
                    "deadline",
                    models.DateTimeField(
                        blank=True,
                        help_text="回答の締め切り日時",
                        null=True,
                        verbose_name="回答期限",
                    ),
                ),
                (
                    "timezone_name",
                    models.CharField(
                        default="Asia/Tokyo",
                        help_text="イベントのタイムゾーン",
                        max_length=50,
                        verbose_name="タイムゾーン",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="イベントが有効かどうか",
                        verbose_name="有効",
                    ),
                ),
                (
                    "allow_maybe",
                    models.BooleanField(
                        default=True,
                        help_text="回答に「△（調整可能）」を許可するか",
                        verbose_name="「△」を許可",
                    ),
                ),
                (
                    "show_participant_count",
                    models.BooleanField(
                        default=True,
                        help_text="参加者の回答数を表示するか",
                        verbose_name="参加者数表示",
                    ),
                ),
                (
                    "notify_on_response",
                    models.BooleanField(
                        default=False,
                        help_text="新しい回答があった時にメールで通知",
                        verbose_name="回答時通知",
                    ),
                ),
                (
                    "is_finalized",
                    models.BooleanField(
                        default=False,
                        help_text="日程が確定したかどうか",
                        verbose_name="確定済み",
                    ),
                ),
                (
                    "meeting_provider",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("google_meet", "Google Meet"),
                            ("teams", "Microsoft Teams"),
                            ("zoom", "Zoom"),
                        ],
                        help_text="自動生成された会議URLのプロバイダー",
                        max_length=50,
                        null=True,
                        verbose_name="会議プロバイダー",
                    ),
                ),
                (
                    "meeting_url",
                    models.URLField(
                        blank=True,
                        help_text="自動生成された会議URL",
                        max_length=500,
                        null=True,
                        verbose_name="会議URL",
                    ),
                ),
                (
                    "meeting_created_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="会議URLが作成された日時",
                        null=True,
                        verbose_name="会議URL作成日時",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "finalized_candidate",
                    models.ForeignKey(
                        blank=True,
                        help_text="確定した候補日程",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="finalized_schedules",
                        to="schedule.candidate",
                        verbose_name="確定日程",
                    ),
                ),
                (
                    "owner_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="ログインユーザーが作成した場合にリンク",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_schedules",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="オーナーユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "予定",
                "verbose_name_plural": "予定",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="参加者の名前", max_length=100, verbose_name="名前"
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="参加者からのコメント",
                        verbose_name="コメント",
                    ),
                ),
                (
                    "edit_token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="移行期間中のみ使用。新規作成では使用しない",
                        unique=True,
                        verbose_name="編集トークン（旧・平文）",
                    ),
                ),
                (
                    "edit_token_hash",
                    models.CharField(
                        blank=True,
                        help_text="回答編集用のトークン（ハッシュ保存）",
                        max_length=256,
                        null=True,
                        verbose_name="編集トークン（ハッシュ）",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="schedule.schedule",
                        verbose_name="予定",
                    ),
                ),
            ],
            options={
                "verbose_name": "参加者",
                "verbose_name_plural": "参加者",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("new_response", "新規回答"),
                            ("deadline_reminder", "期限リマインダー"),
                            ("finalized", "日程確定"),
                        ],
                        max_length=20,
                        verbose_name="通知タイプ",
                    ),
                ),
                (
                    "recipient_email",
                    models.EmailField(max_length=254, verbose_name="送信先"),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="件名")),
                ("body", models.TextField(verbose_name="本文")),
                (
                    "sent_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="送信日時"),
                ),
                (
                    "is_sent",
                    models.BooleanField(default=False, verbose_name="送信済み"),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="エラーメッセージ"
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="schedule.schedule",
                        verbose_name="予定",
                    ),
                ),
            ],
            options={
                "verbose_name": "通知",
                "verbose_name_plural": "通知",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.AddField(
            model_name="candidate",
            name="schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidates",
                to="schedule.schedule",
                verbose_name="予定",
            ),
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "◯"),
                            ("maybe", "△"),
                            ("ng", "×"),
                            ("pending", "未回答"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="出欠",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="schedule.candidate",
                        verbose_name="候補日程",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="schedule.participant",
                        verbose_name="参加者",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="schedule.schedule",
                        verbose_name="予定",
                    ),
                ),
            ],
            options={
                "verbose_name": "出欠",
                "verbose_name_plural": "出欠",
            },
        ),
        migrations.AddIndex(
            model_name="schedule",
            index=models.Index(fields=["uuid"], name="schedule_sc_uuid_afd045_idx"),
        ),
        migrations.AddIndex(
            model_name="schedule",
            index=models.Index(
                fields=["created_at"], name="schedule_sc_created_bada1d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="schedule",
            index=models.Index(
                fields=["is_active", "is_finalized"],
                name="schedule_sc_is_acti_560a1e_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="participant",
            unique_together={("schedule", "name")},
        ),
        migrations.AddIndex(
            model_name="candidate",
            index=models.Index(
                fields=["schedule", "order"], name="schedule_ca_schedul_b13e32_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["schedule", "candidate"], name="schedule_at_schedul_2f2d6c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["participant", "status"], name="schedule_at_partici_32c5ea_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("participant", "candidate")},
        ),
    ]
