# Generated by Django 5.1 manually

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='finalized_at',
            field=models.DateTimeField(blank=True, help_text='日程が確定された日時', null=True, verbose_name='確定日時'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='closed_at',
            field=models.DateTimeField(blank=True, help_text='回答が締め切られた日時', null=True, verbose_name='締切日時'),
        ),
    ]
